Repository jdwilkin4/contrast-ratio-repo, pull requests merged in 2022-09, with the labels that each got.

#97 Feat: user message for invalid RGB input
  index.html
  index.js
  styles.css
Labels: feature

#115 minor fix: css margin-bottom property
  styles.css
Labels: fix

#123 Fix Error message showing up for valid HSL inputs
  index.js
Labels: fix

#110 refactor: Modifications on result row
  index.html
  styles.css
Labels: refactor

#129 Chore - Update index.html #118
  index.html
Labels: chore

#130 chore: hsla rgba functionality removed
  index.js
Labels: chore

#143 Chore: updated urls in package json
  package.json
Labels: chore

#124 fix: error message showing for valid named colors
  index.html
  index.js
  styles.css
Labels: bug

#132 feat: dynamically add graphics content
  index.html
  index.js
  styles.css
Labels: feature

#144 Fix content overflow on smaller screens
  styles.css
Labels: fix

#133 Handling HSL invalid input errors
  index.js
Labels: feature

#145 feat: dynamically add styles for pass fail status
  index.html
  index.js
  styles.css
Labels: feature
