Repository jdwilkin4/contrast-ratio-repo, pull requests merged in 2022-08, with the labels that each got.

#42 feat: adding pass fail icons
  index.html
Labels: question

#45 fix: remove for attribute from inputs
  index.html
Labels: fix

#55 fix html-from-validator-report
  index.html
Labels: fix

#50 chore: dynamically add the year using JavaScript
  index.html
  index.js
Labels: chore, WIP

#41 docs: prerequisites section added
  README.md
Labels: documentation

#47 chore: added a pr template
  .github/pull_request_template.md
Labels: chore

#61 feat: dynamic change of colors in swatches
  index.html
  index.js
Labels: feature

#58 style: applied some font styles
  index.html
  styles.css
Labels: style

#71 Feat: implemented rgb and rgba functionality
  index.js
Labels: feature, WIP

#73 docs: add CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: documentation

#74 docs: add forking instructions to README file
  README.md
Labels: documentation

#78 Feat: user message for invalid input
  index.html
  index.js
  styles.css
Labels: feature, WIP

#96 fixed: console errors for svg icons
  index.html
Labels: fix

#104 feature: two named colors functionality
  helpers.js
  index.html
  index.js
Labels: feature

#105 Add AA+ and AAA+ text
  index.html
  styles.css
Labels: chore

#101 Added examples of correct input for each color format #75
  index.html
Labels: chore

#98 Modified the section .primary element #83
  index.html
  styles.css
Labels: refactor

#103 Remove console log statements
  index.js
Labels: chore
